// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw4bKJF_4DXLWky7dbLJDnVfpeKazIozI',
    appId: '1:279279489966:web:b3e34ce8d85d122ed62e3f',
    messagingSenderId: '279279489966',
    projectId: 'recipe-3fc99',
    authDomain: 'recipe-3fc99.firebaseapp.com',
    storageBucket: 'recipe-3fc99.appspot.com',
    measurementId: 'G-0VH7B4382M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnisv2QQigS2k_RgXmPwjxN3gIIeS2RXg',
    appId: '1:279279489966:android:07f40220e6367bd4d62e3f',
    messagingSenderId: '279279489966',
    projectId: 'recipe-3fc99',
    storageBucket: 'recipe-3fc99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7fZPe5AB6j58BMQF9oUchgSsPZ_gFKBc',
    appId: '1:279279489966:ios:ebec3491bdea78add62e3f',
    messagingSenderId: '279279489966',
    projectId: 'recipe-3fc99',
    storageBucket: 'recipe-3fc99.appspot.com',
    iosBundleId: 'com.example.recipe',
  );
}
